name:   Ol√° Mundo
on: push
jobs:
    ola-mundo:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ls -la
            - run: bash meu-script.sh
            env:
                NOME_SISTEMA: "Sieg"